people = ["Confucius"
, "Cleopatra"
, "Leonardo da Vinci"
, "Isaac Newton"
, "Albert Einstein"
, "William Shakespeare"
, "Marie Curie"
, "Mahatma Gandhi"
, "Nelson Mandela"
, "Aristotle"
, "Charles Darwin"
, "Galileo Galilei"
, "Martin Luther King Jr."
, "Mother Teresa"
, "Socrates"
, "Abraham Lincoln"
, "Winston Churchill"
, "Charles Dickens"
, "Alexander the Great"
, "Plato"
, "Johannes Gutenberg"
, "Steve Jobs"
, "Alexander Fleming"
, "Thomas Edison"
, "Louis Pasteur"
, "Queen Elizabeth II"
, "Muhammad Ali"
, "Rosa Parks"
, "Winston Churchill"
, "Amelia Earhart"
, "Queen Victoria"
, "Jane Austen"
, "Pablo Picasso"
, "Vincent van Gogh"
, "Fidel Castro"
, "Margaret Thatcher"
, "Beethoven"
, "Wolfgang Amadeus Mozart"
, "Henry Ford"
, "Karl Marx"
, "Vladimir Lenin"
, "Mahatma Gandhi"
, "Ben Franklin"
, "George Washington"
, "George Orwell"
, "Joan of Arc"
, "Christopher Columbus"
, "Thomas Jefferson"
, "Alexander Hamilton"
, "Thomas Aquinas"
, "Aristotle"
, "Immanuel Kant"
, "Karl Popper"
, "John Locke"
, "Thomas Hobbes"
, "Emily Dickinson"
, "Albert Camus"
, "William Faulkner"
, "Leo Tolstoy"
, "Mark Twain"
, "Charles Dickens"
, "George Eliot"
, "Homer"
, "Virginia Woolf"
, "Ernest Hemingway"
, "John Steinbeck"
, "Harper Lee"
, "Martin Luther"
, "Saint Augustine"
, "Mahavira"
, "Laozi"
, "Sun Tzu"
, "Ibn Khaldun"
, "Ibn Sina (Avicenna)"
, "Rumi"
, "Rabindranath Tagore"
, "Nelson Mandela"
, "Desmond Tutu"
, "Martin Luther King Jr."
, "Malala Yousafzai"
, "Albert Schweitzer"
, "Florence Nightingale"
, "Susan B. Anthony"
, "Marie Curie"
, "Clara Barton"
, "Rosa Parks"
, "Amelia Earhart"
, "Mother Teresa"
, "Aung San Suu Kyi"
, "Eleanor Roosevelt"
, "Queen Elizabeth I"
, "Queen Isabella I of Castile"
, "Catherine the Great"
, "Empress Wu Zetian"
, "Hatshepsut"
, "Anne Frank"
, "Sojourner Truth"
, "Harriet Tubman"
, "Oprah Winfrey"
, "Bill Gates"]
